### ISSUE TITLE
Manglende bibtex entries

### ISSUE THREAD

**Issue by jamesavery** [jamesavery/SASS#5]
Warning--I didn't find a database entry for "ringartefacts"
Warning--I didn't find a database entry for "beam-hardening"
Warning--empty journal in phasecontrast

@a-topic jeg tror, det er dig, der havde dem?

**Comment by a-topic** [comment]
Ah "ringartefacts" er stavet britisk i brødteksten, men amerikansk "ringartifacts" i bibtex.
derudover er "beam-hardening" -> "beamhardening" i bibtex
og "phasecontrast" manglede feltet `journal`.

er fikset nu
